### PR TITLE
Adds options for lowUpperBound and highLowerBound for HTML reports

### LINKED ISSUE #14: Add options to process the lowUpperBound and highLowerBound options for HTML output
When using this tool to merge coverage reports, you cannot specify the `lowUpperBound` and `highLowerBound` options which are used to customise this report. The tool should add some (optional) command line parameters to be able to set these values

### PR DESCRIPTION
**Pull request by carlos-granados**
- Adds these options to the command and passes them to the HTML writer
- Includes a new test that tests the processing of these options
- Includes the relevant changes to the readme

Fixes #14

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @carlos-granados,

Thank you for your patch. I added some slight changes but I'm unable to edit/push them to your pull request. Is there any chance that you enable editing of your pull request (for me)?

**Comment by carlos-granados** [comment]
Hi, the forked repo is in under my organisation so I'ld rather not give you access. But if you can add some comments to the PR I can implement the changes. Would that work?

**Comment by IchHabRecht** [comment]
Hi @carlos-granados,

I pushed my changes into a new branch in this repo https://github.com/Nimut/phpunit-merger/tree/add-bounds-options

**Comment by carlos-granados** [comment]
@IchHabRecht  great, thank you for these changes 🥇  How do you want to proceed, would you like me to add these changes to our fork and update this PR or do you prefer to merge your branch?

**Comment by IchHabRecht** [comment]
@carlos-granados I will resolves the phpunit issue for v5.x and push again. Maybe you can change your pull request afterwords and I can welcome you as a new contributer ;-)

**Comment by carlos-granados** [comment]
@IchHabRecht brilliant, just let me know when it's ready

**Comment by IchHabRecht** [comment]
@carlos-granados ready ;-)

**Comment by carlos-granados** [comment]
@IchHabRecht this is now ready.

**Comment by carlos-granados** [comment]
@IchHabRecht thanks for merging this. When do you plan to create a new release which includes this code?

**Comment by IchHabRecht** [comment]
@carlos-granados Just waited for Travis to be ready. Released version 1.1.0

**Pull request merged**
