### PR TITLE
adds support for php-code-coverage 8

### PR DESCRIPTION
**Pull request by denizsokullu**

### CODE REVIEW

**Comment by denizsokullu** [comment]
This allows projects to install phpunit 9.x for their testing and still be able to use this.

**Comment by denizsokullu** [comment]
@IchHabRecht can you help with figuring out the build errors? I am not super familiar with how you guys set it up.

**Comment by IchHabRecht** [comment]
Hi @denizsokullu,

Thank you for your contribution. I will release a new version with the updated compatibility.

**Comment by denizsokullu** [comment]
Thanks so much!

**Pull request merged**
